version: '3.8'
services:
  # Frontend NextJS
  web:
    container_name: codelibrary_web
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
