version: '3.7'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
