version: '3.7'
services:
  php:
    container_name: 'backend_php'
    build: .
    restart: unless-stopped
    volumes:
      - ./apps/cms:/app
    networks:
      - internal
    labels:
      - traefik.enable=false

  codelibrary:
    container_name: 'backend_app'
    image: nginx:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - php
    volumes:
      - ./logs:/var/log/nginx:delegated
      - './apps/cms:/app'
      - './site_codelibrary.conf:/etc/nginx/conf.d/default.conf'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codelibrary.rule=Host(`backend.localhost`)'
      - 'traefik.http.services.codelibrary.loadbalancer.server.port=80'
    networks:
      - internal
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1

  traefik:
    container_name: 'backend_loadbalancer'
    image: 'traefik:v2.8.1'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - internal
    depends_on:
      - backend_app
      - backend_php
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=traefik'
      - 'traefik.http.routers.api.entrypoints=web'
      - 'traefik.http.routers.api.rule=Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.redirect-router.entrypoints=web'
      - 'traefik.http.routers.redirect-router.rule=Host(`frontend.localhost`)'
      - 'traefik.http.routers.redirect-router.middlewares=redirect-regex'
      - 'traefik.http.middlewares.redirect-regex.redirectregex.regex=(.)*'
      - 'traefik.http.middlewares.redirect-regex.redirectregex.replacement=http://localhost:3000'
      - 'traefik.http.middlewares.redirect-regex.redirectregex.permanent=false'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - ./traefik.yml:/traefik.yml:ro
networks:
  internal:
