version: '3.8'
services:
  # Frontend
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   restart: always
  #   ports:
  #     - 3000:3000

  # CMS
  cms_caddy:
    container_name: cms_caddy
    image: caddy:2.6.2
    restart: unless-stopped
    networks:
      - default
      - traefik-dynamic
    volumes:
      - codelibrary:/srv/
      - ./deploy/hfg/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - cms_php_fpm
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codelibrary.rule=Host(`${BACKEND_HOST}`)'
      - 'traefik.http.services.codelibrary.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.codelibrary-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.codelibrary.middlewares=codelibrary-https-redirect'
      - 'traefik.docker.network=traefik-dynamic'
      # No indexation eg. google
      - 'traefik.http.middlewares.traefik-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex'

  cms_composer_installation:
    container_name: cms_composer_installation
    image: composer
    user: '1000:1000'
    networks:
      - default
    volumes:
      - codelibrary:/app
    command: composer install --ignore-platform-reqs

  cms_php_fpm:
    container_name: cms_php_fpm
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - default
    volumes:
      - codelibrary:/srv/
      - ./.user.ini:/usr/local/etc/php/conf.d/.user.ini
    depends_on:
      - cms_composer_installation

volumes:
  codelibrary:
    name: codelibrary
    driver: local
    driver_opts:
      type: cifs
      device: '//${BACKEND_SHARE_REMOTE_DOMAIN}/${BACKEND_SHARE_PATH_TO_LIBRARY}'
      o: 'addr=${BACKEND_SHARE_REMOTE_HOST},username=${BACKEND_SHARE_USER},password=${BACKEND_SHARE_PASSWORD},file_mode=0777,dir_mode=0777,vers=3.0'
networks:
  default:
  traefik-dynamic:
    external: true
