title: Site

options:
  preview: "{{ kirby.option('frontendUrl') }}"

columns:
  main:
    width: 2/3
    sections:
      pages:
        type: pages
        layout: list
        template: layout
      navigation:
        type: fields
        fields:
          navigation:
            label: Navigation
            type: navigation
            levels: 1
            help: Main navigation
          footerInternal:
            label: Footer Internal Links
            type: navigation
            levels: 1
            help: Footer internal navigation in the first column
          footerExternal:
            label: Footer External Links
            type: navigation
            levels: 1
            help: Footer external navigation links e.g. "https://hfg-gmuend.de"
  meta:
    width: 1/3
    type: fields
    fields:
      categories:
        type: structure
        label: Kategorien
        fields:
          title:
            label: Titel
            type: text
          description:
            label: Beschreibung
            type: textarea
      languages:
        type: tags
        label: Programming Languages
        # even if its not used to change via the backend, its needed for the search.php controller
      courses:
        type: structure
        label: Courses
        fields:
          course:
            label: Coursename
            type: text
