version: '3.8'
services:
  # Frontend
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   restart: always
  #   ports:
  #     - 3000:3000

  # CMS
  cms_caddy:
    container_name: cms_caddy
    # image: kirby-docker:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - my-bridge-network
    ports:
      - '80:80'
    volumes:
      - codelibrary:/srv/
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codelibrary.rule=Host(`${BACKEND_HOST}`)'
      - 'traefik.http.services.codelibrary.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.codelibrary-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.codelibrary.middlewares=codelibrary-https-redirect'
      - 'traefik.docker.network=traefik-dynamic'
      # No indexation eg. google
      - 'traefik.http.middlewares.traefik-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex'

volumes:
  codelibrary:
    name: codelibrary
    driver: local
    driver_opts:
      type: 'cifs'
      device: '//${BACKEND_SHARE_REMOTE_DOMAIN}/${BACKEND_SHARE_PATH_TO_LIBRARY}'
      o: 'addr=${BACKEND_SHARE_REMOTE_IP},username=${BACKEND_SHARE_USER},password=${BACKEND_SHARE_PASSWORD}'
networks:
  my-bridge-network:
    external: true
