version: '3.8'
services:
  # CMS Kirby
  php:
    container_name: 'codelibrary_php'
    build:
      dockerfile: ../../apps/cms/Dockerfile
      context: ../../apps/cms
    restart: unless-stopped
    volumes:
      - ../../apps/cms/assets:/srv/assets/
      - ../../apps/cms/media:/srv/media/
      - ../../apps/cms/site:/srv/site/
      - ../../apps/cms/storage:/srv/storage/
      - ../../apps/cms/index.php:/srv/index.php:ro
      - ./.env:/srv/.env:ro
    env_file:
      - .env
    networks:
      - internal

  codelibrary:
    container_name: 'codelibrary_cms'
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes:
      - ../../apps/cms/assets:/srv/assets/
      - ../../apps/cms/media:/srv/media/
      - ../../apps/cms/site:/srv/site/
      - ../../apps/cms/storage:/srv/storage/
      - ../../apps/cms/index.php:/srv/index.php:ro
      - ./.env:/srv/.env:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - internal
    env_file:
      - .env

networks:
  internal:
