version: '3.7'
services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../../deploy/local/Caddyfile:/etc/caddy/Caddyfile
      - ../../site/:/srv/site/
      - ../../kirby/:/srv/kirby/
      - ../../vendor/:/srv/vendor/
      - ../../storage/:/srv/storage/
      - ../../media/:/srv/media/
      - ../../index.php:/srv/index.php
    env_file:
      - ../../.env
    depends_on:
      - php-fpm

  composer_installation:
    container_name: composer_installation
    image: composer
    user: '1000:1000'
    volumes:
      - ../../:/app
    command: composer install --ignore-platform-reqs

  php-fpm:
    container_name: php-fpm
    build: .
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - .user.ini:/usr/local/etc/php/conf.d/.user.ini
      - ../../site/:/srv/site/
      - ../../kirby/:/srv/kirby/
      - ../../vendor/:/srv/vendor/
      - ../../storage/:/srv/storage/
      - ../../media/:/srv/media/
      - ../../index.php:/srv/index.php
      # - phpinfo.php:/srv/phpinfo.php
    depends_on:
      - composer_installation

networks:
  default:
    name: main
